# 异常

Java使用一种称为*异常处理*的错误捕获机制处理程序的错误情况。如果某个方法不能够采用正常途径完成它的任务，就可以通过另一种路径退出方法。这种情况下，方法并不返回任何值，而是抛出一个封装了错误信息的推向。抛出时，方法会立刻退出，调用这个方法的相关代码也无法继续执行，取而代之的是异常处理机制开始搜索能够处理这种异常状况的异常处理器。

在Java中的异常有自己特定的语法和继承结构。所有异常都是派生自`Throwable`类的一个实例，然后细分为`Error`和`Exception`两个分支。

* Error：描述了Java运行时系统的内部错误和资源耗尽错误。应用程序不应该抛出这种错误，如果出现则应该告知用户出现错误，然后使程序安全的退出。

* Exception：该分支又细分为`RuntimeException`和其他异常两个分支。由应用程序错误导致的异常属于`RuntimeException`；而程序本身没有问题，出于例如IO导致的异常（`IOException`）等等则属于其他。

* 接查（checked）异常和非受查（unchecked）异常：所有派生自`Error`和`Exception`的异常称为unchecked异常，其他的称为checked异常。一个方法必须声明所有可能抛出的checked异常，而unchecked异常要么不可控（`Error`），要么就应该避免发生（`RuntimeException`）。


```
异常的继承结构（部分分支没有继续展开）

Throwable
    ├── Error
    |   ├── VirtualMachineError
    |   |   ├── InternalError
    |   |   ├── OutOfMemoryError
    |   |   ├── StackOverflowError
    |   |   └── UnknownError
    |   ├── IOError
    |   ├── AnnotationFormatError
    |   ├── AssertionError
    |   ├── AWTError
    |   ├── ThreadDeath
    |   └── ...
    └── Exception
        ├── RuntimeException
        |   ├── NulPointerException
        |   ├── ArrayIndexOutOfBoundsException
        |   ├── ArithmeticException
        |   ├── ClassCastException
        |   ├── IllegalArgumentException
        |   └── ...
        └── others
            ├── IOException
            |   ├── EOFException
            |   ├── FileNotFoundException
            |   ├── SocketException
            |   └── ...
            └── ...
```

## 自定义异常

...

## 抛出异常

throw和throws

## 捕获异常

try-catch结构 

try-catch-finally结构 

try-catch-finally结构的嵌套

try-with-resource结构



说明：

当finally子句可以包含return语句。如果try语句块使用return退出，同时finally中也包含return，那么在返回前finally子句返回的值将覆盖原始的返回值。

